@startuml
left to right direction

actor "Visitante" as Guest
actor "Usuario registrado" as User
actor "Vendedor" as Seller
actor "Administrador" as Admin

rectangle "Frutalia" {

    ' --- Acceso público ---
    Guest --> (Ver productos)
    Guest --> (Buscar productos)
    Guest --> (Registrarse)

    ' --- Usuario registrado ---
    User --> (Comprar producto)
    User --> (Seleccionar punto de encuentro)
    User --> (Valorar producto)
    User --> (Valorar vendedor)
    User --> (Gestionar perfil)

    ' --- Vendedor (registrado) ---
    Seller --> (Publicar producto)
    Seller --> (Editar producto)
    Seller --> (Eliminar producto)
    User --> (Comprar producto)
    User --> (Seleccionar punto de encuentro)
    User --> (Valorar producto)
    User --> (Valorar vendedor)
    User --> (Gestionar perfil)


    ' --- Admin ---
    Admin --> (CRUD usuarios)
    Admin --> (CRUD productos)

    ' --- Herencia de actor ---
    User --|> Guest
    Seller --|> User
    Admin --|> Seller

}

@enduml